@WildRiftCounterLab.Api_HostAddress = http://localhost:5069

###

POST {{WildRiftCounterLab.Api_HostAddress}}/api/draft/recommendations
Content-Type: application/json

{
  "role": "Baron",
  "laneEnemy": "Darius",
  "enemyTeam": ["Senna", "Jhin", "Olaf"]
}

###

GET {{WildRiftCounterLab.Api_HostAddress}}/api/champions